/*
       Example of HTML code generated by the fonction addSlider()
        <label>Count : <output data-name="pjs_count" for="pjs_count"></output>
            <input type="range" min="1" max="100"  step="1" value="50" class="slider" id="pjs_count">
        </label>
    */
function addSlider( fieldname, domtarget, start, end, value, step, label, callback, init=null ) {
  let xlabel = document.createElement('label');
  xlabel.innerHTML = label + ' : ';
  let xoutput = document.createElement('output');
  xoutput.setAttribute('for', 'pjs_'+fieldname);

  if (init != null) {
    xoutput.value = init;
  } else {
    xoutput.value = value;
  }
  xlabel.append(xoutput);
  let xinput = document.createElement('input');
  xinput.setAttribute('type', 'range');
  xinput.setAttribute('min', start);
  xinput.setAttribute('max', end);
  xinput.setAttribute('step', step);
  xinput.setAttribute('class', 'slider');
  xinput.setAttribute('id', 'pjs_'+fieldname);
  xinput.value = value;
  xlabel.append(xinput);
  domtarget.append(xlabel);
  xinput.addEventListener('change', function(evt) {
    let output = evt.target.parentNode.querySelector('output');
    let substition = callback(this);
    if (substition) {
      output.value = substition;
    } else {
      output.value = this.value;
    }
  }, false)
}

function multiSliders(dom_target, filters, data_form) {
  var form = document.getElementById(dom_target);
  if (form) {
    filters.forEach(item => {
        addSlider(item.field, form, item.min, item.max, item.value, item.step, item.label, item.callback, item.init || null);
        data_form['pjs_'+item.field] = item.value;
    });
  } else {
    console.error('Dom item not found on ID : '+dom_target);
  }

}
